<?php
/**
 * This file is part of monda-worker.
 *
 * @contact  mondagroup_php@163.com
 *
 */
namespace app\exception;

use framework\exception\ExceptionHandler;
use framework\http\Request;
use framework\http\Response;
use Throwable;

/**
 * Class Handler
 * @package app\exception
 */
class Handler extends ExceptionHandler
{
    public $ignoreReport = [
        AuthException::class,
    ];

    /**
     * @param Request $request
     * @param Throwable $e
     * @return Response
     */
    public function render(Request $request, Throwable $e): Response
    {
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
