<?php
/**
 * This file is part of monda-worker.
 *
 * @contact  mondagroup_php@163.com
 *
 */
namespace App\Exception;

use Framework\Core\ExceptionHandler;
use Framework\Http\HttpRequest;
use Throwable;

/**
 * Class Handler
 * @package App\exception
 */
class Handler extends ExceptionHandler
{
    public $ignoreReport = [
        AuthException::class,
    ];

    /**
     * @param HttpRequest $request
     * @param Throwable $e
     * @return mixed
     */
    public function render(HttpRequest $request, Throwable $e): mixed
    {
        if (method_exists($e, 'render')) {
            return $e->render();
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
